name: BetterEconomy
main: com.m0pt0pmatt.bettereconomy.BetterEconomy
version: 0.6
softdepend: [Vault, WorldGuard]
commands:
    deposit:
        description: Deposit money
    withdraw:
        description: Withdraw a physical currency
    wealth:
        description: Displays how much money you are carrying in physical currencies
    value:
        description: Displays how much an amount of a certain currency is worth
    money:
        description: Displays how much money is in your account
    setbalance:
        description: Server command. Sets a balance. Creates an account if one does not exist
    pay:
        description: Pay a player a certain amount
    top:
        description: See the players with the highest accounts
    createbank:
        description: Creates a bank.
    evaluateeconomy:
        description: evaluates currency (ore) distribution over a selection